### ISSUE TITLE
adobe xd code bug on flutter 2.2

### ISSUE THREAD

**Issue by athlona64** [AdobeXD/xd-to-flutter-plugin#120]
## Bug Description

after migrate to flutter 2.2 i found my widget error code generate from xd 

## Console Output

```======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
BoxConstraints has NaN values in minWidth and maxWidth.

These invalid constraints were provided to RenderDecoratedBox's layout() function by the following function, which probably computed the invalid constraints in question:
  RenderPinned.performLayout (package:adobe_xd/pinned.dart:282:9)
The offending constraints were: BoxConstraints(NaN<=w<=NaN, h=673.4; NOT NORMALIZED)
The relevant error-causing widget was: 
  Pinned file:///C:/src/oil_new/LikeWalletPharse3/lib/screen/navigationbar/home/home_screen.dart:262:22
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:517:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:541:19)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:565:6)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1679:24)
#4      RenderPinned.performLayout (package:adobe_xd/pinned.dart:282:9)

```
## Versions:

```[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.1052], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter
    • Framework revision f4abaa0735 (11 days ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\prapa\AppData\Local\Android\Sdk
    • Platform android-S, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\prapa\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code (version 1.50.1)
    • VS Code at C:\Users\prapa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • HD1900 (mobile) • 29ed8a0a • android-arm64  • Android 10 (API 29)
    • Chrome (web)    • chrome   • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)      • edge     • web-javascript • Microsoft Edge 91.0.864.67

! Doctor found issues in 1 category.
```

## Screenshot
![Capture](https://user-images.githubusercontent.com/3031787/125390752-91de5500-e3cd-11eb-8c73-aacdd1edd48b.PNG)

**Comment by gskinner** [comment]
Weird, seems to be appending "w" and "h" to the output values. Have you tested with the latest plugin (v2.0.0) — it no longer uses `Pinned.fromSize`, so I suspect this is no longer an issue. Please reopen if it's still happening in v2. Thanks!
