### ISSUE TITLE
Plugin TypeError: Cannot read property 'a' of null

### ISSUE THREAD

**Issue by Bilonik** [AdobeXD/xd-to-flutter-plugin#75]
**Describe the Bug**
While exporting a component or all the artboard

Plugin TypeError: Cannot read property 'a' of null
    at Object.e.getARGBHexWithOpacity (<settings>/plugins/6eaf77ea/main.js:1:1489)
    at s (<settings>/plugins/6eaf77ea/main.js:1:9016)
    at new d (<settings>/plugins/6eaf77ea/main.js:1:40373)
    at Function.create (<settings>/plugins/6eaf77ea/main.js:1:40178)
    at E (<settings>/plugins/6eaf77ea/main.js:1:72681)
    at P (<settings>/plugins/6eaf77ea/main.js:1:73861)
    at E (<settings>/plugins/6eaf77ea/main.js:1:72805)
    at e.parse (<settings>/plugins/6eaf77ea/main.js:1:72090)
    at Object.exportSelected (<settings>/plugins/6eaf77ea/main.js:1:70230)
    at async exportSelected (<settings>/plugins/6eaf77ea/main.js:1:47475)

**OS & XD Version:**
 - OS: MacOS 10.15.6
 - XD: 32.2.22.2

**Comment by gskinner** [comment]
Any chance you can share the XD file that's causing this (ideally simplified as much as possible)? It looks like something in the file is returning a null color, which we can add a broad catch for to eliminate the error, but I'd like to understand exactly when it is occurring to ensure we are handling it correctly (ex. should it default to black? Transparent? Be omitted?).

Thanks!

**Comment by gskinner** [comment]
Closing, because I believe this was fully resolved in v1.1.0.
